name: sizeComparison

on:
  push:
    branches:
      - main
      - vnext-tokens
  pull_request:
    branches:
      - main
      - vnext-tokens

jobs:
  archiveHeadBuild:
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh 'ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/headBuild archive'
      run: scripts/xcodebuild_wrapper.sh ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/headBuild archive
    - name: Create size file
      run: du -sk $GITHUB_WORKSPACE/headBuild.xcarchive/Products/Applications/FluentUI.Demo.app | cut -f1 >> $GITHUB_WORKSPACE/headSize
    - name: Upload head size artifact
      uses: actions/upload-artifact@v3
      with:
        name: headSize
        path: headSize
  archiveBaseBuild:
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps: 
    - uses: actions/checkout@v3
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh 'ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/baseBuild archive'
      run: scripts/xcodebuild_wrapper.sh ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/baseBuild archive
    - name: Create size file
      run: du -sk $GITHUB_WORKSPACE/baseBuild.xcarchive/Products/Applications/FluentUI.Demo.app | cut -f1 >> $GITHUB_WORKSPACE/baseSize
    - name: Upload base size artifact
      uses: actions/upload-artifact@v3
      with:
        name: baseSize
        path: baseSize
  printSizes:
    runs-on: macos-11
    strategy:
      fail-fast: true
    needs: [archiveHeadBuild, archiveBaseBuild]
    steps:
    - uses: actions/checkout@v3
    - name: Download head artifact
      uses: actions/download-artifact@v3
      with:
        name: headSize
    - name: Download base artifact
      uses: actions/download-artifact@v3
      with:
        name: baseSize
    - name: Print out directoy
      run: ls -la
    - name: ls head
      run: ls -la headSize
    - name: ls base
      run: ls -la baseSize
    - name: Compare sizes
      run: scripts/compare_demo_sizes.sh