name: sizeComparison

on:
  push:
    branches:
      - main
      - vnext-tokens
  pull_request:
    branches:
      - main
      - vnext-tokens

jobs:
  archiveOldBuild:
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh 'ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/oldBuild archive'
      run: scripts/xcodebuild_wrapper.sh ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/oldBuild archive
    - name: print contents of directory
      run: ls -la $GITHUB_WORKSPACE
    - name: print size
      run: du -sk $GITHUB_WORKSPACE/oldBuild.xcarchive/Products/Applications/FluentUI.Demo.app
  archiveNewBuild:
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps: 
    - uses: actions/checkout@v2
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh 'ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/newBuild archive'
      run: scripts/xcodebuild_wrapper.sh ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/newBuild archive
  printSizes:
    runs-on: macos-11
    strategy:
      fail-fast: true
    needs: [archiveOldBuild, archiveNewBuild]
    steps:
    - name: print contents of directory
      run: ls -la $GITHUB_WORKSPACE
    - name: print old size
      run: du -sk $GITHUB_WORKSPACE/oldBuild.xcarchive/Products/Applications/FluentUI.Demo.app
    - name: print new size
      run: du -sk $GITHUB_WORKSPACE/newBuild.xcarchive/Products/Applications/FluentUI.Demo.app
