name: Create PR

on: 
  push:
    branches:
      - huwilkes/PRActions*
jobs:
  Localize:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Create Pull Request
      run: git checkout -b "huwilkes/PRActions`date +%s`"; git push; gh pr create -B huwilkes/PRActions -H huwilkes/PRActions`date +%s` --title "Test PR actions" --body "still testing" -l "Automated PR"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
