name: Create PR

on: 
  push:
    branches:
      - huwilkes/PRActions*
jobs:
  Localize:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Create Pull Request
      run: scripts/create_localization_pr `date +%s`
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
