name: uploadSizeArtifact

on:
  workflow_call:
    inputs:
      sha:
        description: 'sha of the commit to sync, build, and upload an artifact for the size of'
        required: true
        type: string

jobs:
  archiveBuildSize:
    runs-on: macos-12
    strategy:
      fail-fast: false
    steps: 
    - uses: actions/checkout@v3 # Checkout repo at sha
      with:
        ref: ${{ inputs.sha }}
    - name: Switch to current version of Xcode
      run: scripts/xcode_select_current_version.sh
    - name: scripts/xcodebuild_wrapper.sh 'ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/sha archive' # Build and archive release device build
      run: scripts/xcodebuild_wrapper.sh ios_device_build Demo.Development Release build -archivePath $GITHUB_WORKSPACE/${{ inputs.sha  }} archive
    - name: Create size file # Get size of demo app in "kilobytes" (2*512B blocks) and store in a file with the hash as the name
      run: du -sk $GITHUB_WORKSPACE/${{ inputs.sha }}.xcarchive/Products/Applications/FluentUI.Demo.app | cut -f1 >> $GITHUB_WORKSPACE/${{ inputs.sha }}
    - name: Upload head size artifact # Upload the file with just the size, ie, 36692
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.sha }}
        path: ${{ inputs.sha }}
